server:
  port: 5210

spring:
  application:
    name: CrystalDispatcher
  web:
    resources:
      static-locations: classpath:static/,file:static/

crystal:
  server:
    # Netty Server Port for nodes
    communication-port: 6210
  node:
    # Cron Expression of "Check Node Alive Status"
    check-alive-cron: 0/5 * * * * ?
    # Cron Expression of "Update Node Information"
    update-node-cron: 0/10 * * * * ?
    # If a node is not assigned a secretKey, use the default-secret-key
    default-secret-key: Q3J5c3RhbEFJTm9kZQ==
    # Specify the secretKey for nodes
    secret-keys:
      - node-name: CrystalNode1
        secret-key: Q3J5c3RhbEFJTm9kZQ==

logging:
  file:
    name: logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-history: 31
      max-file-size: 4GB
      file-name-pattern: ${LOG_FILE}_%d{yyyy-MM-dd}_%i.gz