server:
  port: 5310

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
crystal:
  dispatcher:
    host: 127.0.0.1
    port: 5210
    ssl: false
  ollama:
    host: localhost
    port: 11434
    ssl: false
    default-model: gemma2:27b
    default-temperature: 0.05
