server:
  port: 5310

spring:
  application:
    name: CrystalNode1
  ai:
    openai:
      api-key: OpenAI-Api-Key

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info

crystal:
  # standalone:
  #   In standalone mode, the RestAPI will be enabled.
  #   To access this instance, you need to call login api with secret-key to get the accessKey.
  # cluster:
  #   In cluster mode, all necessary properties in crystal.dispatcher should be completed.
  #   Also, the RestAPI will be disabled.
  mode: cluster

  # Only when the dispatcher is given the same secretKey will the node will respond properly.
  secret-key: Q3J5c3RhbEFJTm9kZQ==
  # Enable SSL
  ssl: false
  dispatcher:
    host: 127.0.0.1
    port: 5210
    ssl: false
  ollama:
    enabled: true
    host: localhost
    port: 11434
    # Enable SSL
    ssl: false
    default-model: gemma2:27b
    default-temperature: 0.05
    max-execution-time-millis: 16000
  deepseek:
    enabled: true
    host: api.deepseek.com
    port: 80
    # Enable SSL
    ssl: true
    api-key: ${DEEPSEEK_API_KEY}
    default-model: deepseek-chat
    default-temperature: 0.1

logging:
  file:
    name: logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-history: 31
      max-file-size: 4GB
      file-name-pattern: ${LOG_FILE}_%d{yyyy-MM-dd}_%i.gz