server:
  port: 5310

spring:
  application:
    name: CrystalNode1

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info

crystal:
  # Only when the dispatcher is given the same secretKey will the node will respond properly.
  secret-key: Q3J5c3RhbEFJTm9kZQ==
  # Enable SSL
  ssl: false
  dispatcher:
    host: 127.0.0.1
    port: 5210
    ssl: false
  ollama:
    host: localhost
    port: 11434
    # Enable SSL
    ssl: false
    default-model: gemma2:27b
    default-temperature: 0.05
    max-execution-time-millis: 16000
